FROM edenfed/transactionhistory:f5f76ca-dirty@sha256:94640f5d3ad5dcffe5898898e27516e01dcff8dab37cc5ebaa657379788ebfd1
COPY ./agent/opentelemetry-javaagent.jar /usr/local/lib/opentelemetry-javaagent.jar
